### ISSUE TITLE
Put on crates.io?

### ISSUE THREAD

**Issue by CDWimmer** [nathaniel-daniel/logitech-led-sdk-rs#41]
Hi there, is there half a chance you could get this put on crates.io? I'm kinda new to rust and adding libs externally is not something I'm sure about, plus it would just generally be easier for everyone :P

**Comment by CDWimmer** [comment]
Ok I tried `cargo install --git https://github.com/nathaniel-daniel/logitech-led-sdk-rs.git` but was met with "error: no packages found with binaries or examples" which seems to relate to what is said here: https://doc.rust-lang.org/cargo/commands/cargo-install.html#description

**Comment by nathaniel-daniel** [comment]
> Hi there, is there half a chance you could get this put on crates.io? I'm kinda new to rust and adding libs externally is not something I'm sure about, plus it would just generally be easier for everyone :P

Yeah sure, let me clean this up a bit first through. Should take a day or two.

> Ok I tried cargo install --git https://github.com/nathaniel-daniel/logitech-led-sdk-rs.git but was met with "error: no packages found with binaries or examples" which seems to relate to what is said here: https://doc.rust-lang.org/cargo/commands/cargo-install.html#description

`cargo install` is for installing programs so that you can use them from the command line. You should look into [`cargo add`](https://doc.rust-lang.org/cargo/commands/cargo-add.html), which adds an entry to your `Cargo.toml` file for the dependency. It's basically `npm i <dep>`.

Also, see the README about some extra files you need to download and set up. I'll see if I can add a feature to do that automatically.

**Comment by CDWimmer** [comment]
Hey! I was literally just logging in to see if you'd responded! Awesome news, thanks!

> cargo install is for installing programs so that you can use them from the command line.

I think I'm just dumb, lol. Thanks again!

Yeah I've grabbed the files from Logitech, there's a similar pair of libraries for Corsair's iCUE ([cue-sdk](https://crates.io/crates/cue-sdk), [cue-sdk-sys](https://crates.io/crates/cue-sdk-sys)) that need's their particular SDK bits too. 

Gotta say I much prefer just adding an environment variable than edditing PATH like `cue-sdk` asks for, so thanks for that decision :) 

All I need is someone to crack Omen lighting, then I can write my own nonsense software to make my random collection of peripherals all flash fun cololours together in harmony 😄

**Comment by nathaniel-daniel** [comment]
> Yeah I've grabbed the files from Logitech, there's a similar pair of libraries for Corsair's iCUE ([cue-sdk](https://crates.io/crates/cue-sdk), [cue-sdk-sys](https://crates.io/crates/cue-sdk-sys)) that need's their particular SDK bits too.
> 
> Gotta say I much prefer just adding an environment variable than edditing PATH like `cue-sdk` asks for, so thanks for that decision :)

Thanks. I was thinking of adding am off-by-default feature named `download-sdk` which would embed a http client and unzipper to grab the sdk for you and use it automatically, to simplify setup when you just want something working. Think that would be too intrusive/too heavyweight?



> All I need is someone to crack Omen lighting, then I can write my own nonsense software to make my random collection of peripherals all flash fun cololours together in harmony 😄

Nice, lol. I think I tried that a while back as well. What Omen peripherals do you have? I have some unfinished code for intercepting light commands from Logitech and piping them to Omen's 4 zone keyboard led controller. I can post if you think it would be helpful. The Omen apps are C# too, so they are pretty easy to decompile and reverse engineer.

**Comment by nathaniel-daniel** [comment]
Fair warning though, Logitech's SDK is pretty bad IMO. From what I can tell, the API is a remnant from the LGS days, though most new things use LGHUB (which is a *lovely* piece of software). It works by exposing a DLL that provides the same functions over both apps, so that the SDK will work with either app. In the LGHUB case, it seems to form a one-way websocket connection to a controller background process that actually makes the command. However, the API is very limited, as there is no way to tell when a command finishes, or if it was even received by the background process. You kinda have to add your own delays and hope nothing goes wrong.

**Comment by CDWimmer** [comment]
> Thanks. I was thinking of adding am off-by-default feature named `download-sdk` which would embed a http client and unzipper to grab the sdk for you and use it automatically, to simplify setup when you just want something working. Think that would be too intrusive/too heavyweight?

Not sure, definitely convenient but at the same time it wasn't exactly difficult to do manually either. I think it would be too easy for Logitech to break at some point by just mildly rearranging their website one day, plus I think a lot of companies tend to not like that sort of thing as it's a little too close to just shipping their property... 


> Nice, lol. I think I tried that a while back as well. What Omen peripherals do you have? I have some unfinished code for intercepting light commands from Logitech and piping them to Omen's 4 zone keyboard led controller. I can post if you think it would be helpful. The Omen apps are C# too, so they are pretty easy to decompile and reverse engineer.

Oh neat, perhaps a future project then. I'm far too inexperienced at the moment but I did see this https://github.com/determ1ne/OmenHubLight where someone had done some C# reverse engineering. (I just have an Omen laptop with the 4-zone keyboard)

**Comment by nathaniel-daniel** [comment]
> I think it would be too easy for Logitech to break at some point by just mildly rearranging their website one day, plus I think a lot of companies tend to not like that sort of thing as it's a little too close to just shipping their property...

Yeah, that was another one of my concerns as well. The license specifies that the SDK has to be downloaded from their website, so I thought an automatic download might be good enough. The risk and hassle of adding all this makes it not worth it though, glad you think its good enough. I'll leave as-is in that case.

**Comment by nathaniel-daniel** [comment]
Released at https://crates.io/crates/logitech-led-sdk and https://crates.io/crates/logitech-led-sdk-sys. Feel free to open more issues if there are any problems.

**Comment by nathaniel-daniel** [comment]
Actually, looks like I finished a lot more of that project than I thought. Would a library that can do the following be sufficient? I'd be willing to polish it a bit and post that part if it is:
```rust
fn main() {
    // set_proxy_blanket(wmi_services).unwrap();

    let start_time = Instant::now();
    let lighting = FourZoneLighting::new().unwrap();
    let four_zone_create_time = Instant::now();
    dbg!(four_zone_create_time - start_time);
    let is_lighting_supported = lighting.is_lighting_supported().unwrap();
    let is_lighting_supported_time = Instant::now();
    let lighting_is_turn_on = lighting.is_turn_on().unwrap();
    dbg!(is_lighting_supported_time - four_zone_create_time);

    dbg!(is_lighting_supported);
    dbg!(lighting_is_turn_on);

    for _ in 0..100 {
        lighting
            .set_zone_colors(&[Color::RED, Color::RED, Color::RED, Color::RED])
            .unwrap();
        std::thread::sleep(std::time::Duration::from_millis(250));

        lighting
            .set_zone_colors(&[Color::GREEN, Color::GREEN, Color::GREEN, Color::GREEN])
            .unwrap();
        std::thread::sleep(std::time::Duration::from_millis(250));

        lighting
            .set_zone_colors(&[Color::BLUE, Color::BLUE, Color::BLUE, Color::BLUE])
            .unwrap();
        std::thread::sleep(std::time::Duration::from_millis(250));
    }
}
```
